# Generated by Django 5.2.8 on 2025-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Depart_Name', models.CharField(max_length=50)),
                ('join_Date', models.DateField()),
            ],
        ),
    ]
